/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Pedro Silva (https://sketchfab.com/pxdrosilva)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/sci-fi-computer-terminal-e03a14fc845e4e2d9573b95e00f79ef4
title: Sci-fi Computer Terminal
*/

import React, { memo, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

function Computer(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/computer.glb');
  useFrame(() => {
    group.current.rotation.y += 0.01;
  });
  return (
    <group {...props} ref={group} dispose={null}>
      <group
        rotation={[Math.PI / 2, -Math.PI, Math.PI / 2]}
        position={[0, -1, 0]}
        scale={1.5}
      >
        <mesh
          geometry={nodes.Cube000_Material009_0.geometry}
          material={materials['Material.009']}
        />
        <mesh
          geometry={nodes.Fio2_Material010_0.geometry}
          material={materials['Material.010']}
        />
        <mesh
          geometry={nodes.Cube001_Material009_0.geometry}
          material={materials['Material.009']}
        />
        <mesh
          geometry={nodes.Fio4_Material008_0.geometry}
          material={materials['Material.008']}
        />
        <mesh
          geometry={nodes.Fio3_Material007_0.geometry}
          material={materials['Material.007']}
        />
        <mesh
          geometry={nodes.Fio1_Material011_0.geometry}
          material={materials['Material.011']}
        />
        <mesh
          geometry={nodes.Bilhete_Material003_0.geometry}
          material={materials['Material.003']}
        />
        <mesh
          geometry={nodes.Keyboard_Material002_0.geometry}
          material={materials['Material.002']}
        />
        <mesh
          geometry={nodes.Container_Material004_0.geometry}
          material={materials['Material.004']}
        />
        <mesh
          geometry={nodes.Copo_Material005_0.geometry}
          material={materials['Material.005']}
        />
        <mesh
          geometry={nodes.Tela_Material012_0.geometry}
          material={materials['Material.012']}
        />
        <mesh
          geometry={nodes.Computer_CPU_0.geometry}
          material={materials.material}
        />
        <mesh
          geometry={nodes.Computer_Monitor_0.geometry}
          material={materials.Monitor}
        />
        <mesh
          geometry={nodes.Computer_Teclado_0.geometry}
          material={materials.Teclado}
        />
        <mesh
          geometry={nodes.Computer_Conect_Fios_0.geometry}
          material={materials.Conect_Fios}
        />
      </group>
    </group>
  );
}
export default memo(Computer);
useGLTF.preload('/computer.glb');
