/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: AnnaBelle Fibonacci (https://sketchfab.com/annabellefibonacci)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/vintage-globe-5ae174f9d26f40b99eebe3427153438f
title: Vintage globe
*/

import React, { memo, useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

function Globe(props) {
  const group = useRef();
  useFrame(() => (group.current.rotation.y += 0.02));

  const { nodes, materials } = useGLTF('/globe.glb');
  return (
    <group {...props} ref={group} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} position={[0, -2, 0]} scale={0.05}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.wire_135110008}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.objects_from_Echo_of_the_Past_Cupboard}
        />
      </group>
    </group>
  );
}

export default memo(Globe);
useGLTF.preload('/globe.glb');
